### ISSUE TITLE
podlet-compose: cannot mix long syntax and short syntax volume declaration

### ISSUE THREAD

**Issue by cyqsimon** [k9withabone/podlet#26]
## TLDR

If you declare some volumes using the short syntax and some others using the long syntax, the ones using the long syntax will fail parsing. <s>I believe this to be an upstream problem in `serde_yaml`.</s>

Using [Frigate](https://docs.frigate.video/frigate/installation/) as an example:

```yaml
version: "3.9"
services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    volumes:
      - type: tmpfs
        target: /tmp/cache
      - /etc/frigate/config.yml:/config/config.yml
```

```bash
$ podlet compose frigate.yaml
Error:
   0: File `frigate.yaml` is not a valid compose file
   1: services.frigate: data did not match any variant of untagged enum Volumes at line 4 column 5

Location:
   src/cli.rs:543
```

---

I have already reported it upstream to stephanbuys/docker-compose-types#31. This issue is just to notify the author(s) and other users of podlet. For more details, see that issue.
