### ISSUE TITLE
Networks are added to the quadlet file with ".network" appended

### ISSUE THREAD

**Issue by NjlsShade** [k9withabone/podlet#48]
When creating a quadlet from a compose file containing one or more network definitions, it will output the resulting container structure with ".network" appended to the end of all networks configured. This is not the correct syntax and will fail.

Given the compose file below:

```
services:
    test:
        container_name: test
        image: test/test:latest
        networks:
            - main
```

The output will be:

```
# test.container
[Container]
ContainerName=test
Image=test/test:latest
Network=main.network

[Install]
WantedBy=default.target
```

This issue does not occur if you provide podlet with podman run arguments insead of a compose file:

Given the command:

`podlet --install podman run --network main test/test:latest`

The output will be:

```
# test.container
[Container]
Image=test/test:latest
Network=main

[Install]
WantedBy=default.target
```

**Comment by k9withabone** [comment]
For compose files, podlet assumes that networks listed for a service are also listed under the top-level `networks:` key. Per the [compose spec](https://github.com/compose-spec/compose-spec/blob/77cc0f9575b560c94ca2a3b94db126c54c9e4759/spec.md#networks), that should always be the case. Technically, the snippet you gave is not a valid compose file.

Podlet will also generate a `.network` quadlet file for each network in the top-level `networks:` key (however, podlet doesn't support external networks for compose files). This is why podlet is adding `.network` to the name of the network for the `Network=` option. If you look at the [quadlet docs](https://docs.podman.io/en/stable/markdown/podman-systemd.unit.5.html#network) for the option, they say you can reference a `.network` quadlet file to use.

For example, to complete your snippet above, if you give podlet the following compose file:

```yaml
services:
    test:
        container_name: test
        image: test/test:latest
        networks:
            - main
networks:
    main:
```

It will produce the output:

```ini
# test.container
[Container]
ContainerName=test
Image=test/test:latest
Network=main.network

---

# main.network
[Network]
```

Representing two quadlet files to be used together.

As a side note, if your goal is to group all containers defined in a compose file into a separate network, this is better achieved with pods. All containers in a pod share a network namespace. First, remove or comment out the network definitions in the compose file. Then use `podlet compose --pod <pod>` which will generate a `.kube` quadlet file and a Kubernetes YAML file.
