### ISSUE TITLE
Supports file merging docker compose files

### ISSUE THREAD

**Issue by bsv9** [k9withabone/podlet#59]
Hi,

It would be nice to add functionality to merge docker compose files.
https://docs.docker.com/compose/multiple-compose-files/merge/

# Steps to reproduce
Create docker-compose.yaml
```
version: '3.4'
services:
  redis:
    image: docker.io/redis:7-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis.env

```
Create docker-compose.override.yaml
```
version: '3.4'
services:
  redis:
    restart: always
```

# Expected behavior
```
# redis.container
[Container]
EnvironmentFile=env/redis.env
Exec=sh -c 'redis-server --appendonly yes --requirepass $$REDIS_PASSWORD'
Image=docker.io/redis:7-alpine

[Service]
Restart=always
```
