### ISSUE TITLE
Enhancement: Tolerate `build:` directive in compose file

### ISSUE THREAD

**Issue by kronenpj** [k9withabone/podlet#70]
K9,

  May I suggest an approach to tolerating `build:` directives in compose files: Utilize the stanza title or `container_name` to infer the name of the local image. For example:
  
```yaml
# redis
netbox-redis:
    container_name: netbox-redis
    hostname: redis
    #image: localhost/netbox-redis:latest
    build: ./valkey
```
Podman compose will generate a container called `netbox-redis` with a `latest` tag. Without the `container_name` tag this image would be created from the current directory and the `netbox-redis` key. If an image isn't found, an error is warranted.

I don't know how much effort this would be but it would add a little compatibility to this excellent tool.
